changelog:
  categories:
    - title: Features
      labels:
        - feature
        - enhancement
        - feat
    - title: Fixes
      labels:
        - fix
        - bug
        - bugfix
    - title: Maintenance
      labels:
        - chore
        - refactor
        - ci
        - build
    - title: Other Changes
      labels:
        - "*"
  exclude:
    labels:
      - skip-changelog
